### ISSUE TITLE
BaseAdpater is not working??

### ISSUE THREAD

**Issue by wyb20151010** [Diolor/Swipecards#126]
i may be wrong?why nobody talk about this question.

**Comment by wyb20151010** [comment]
Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference .
when i use baseadapter ,this damn bug will show。someone can help me??/

**Comment by ahmadmiraj** [comment]
i am having the same issue i using a custom adapter to populate the data and facing the same issue...can u help me out ??
or do u have any alternate of this library ??

**Comment by alexwalterbos** [comment]
@wyb20151010 the problem is in your own code. Please post the code where this error is thrown.

**Comment by ahmadmiraj** [comment]
here is a error log
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.lorentzos.swipecards.example, PID: 12317
                                                                                  java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
                                                                                      at com.lorentzos.flingswipe.SwipeFlingAdapterView.makeAndAddView(SwipeFlingAdapterView.java:148)
                                                                                      at com.lorentzos.flingswipe.SwipeFlingAdapterView.layoutChildren(SwipeFlingAdapterView.java:132)
                                                                                      at com.lorentzos.flingswipe.SwipeFlingAdapterView.onLayout(SwipeFlingAdapterView.java:117)
                                                                                      at android.view.View.layout(View.java:15596)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                      at android.view.View.layout(View.java:15596)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                      at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
                                                                                      at android.view.View.layout(View.java:15596)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                      at android.view.View.layout(View.java:15596)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by ahmadmiraj** [comment]
it is a piece of code where it throws exceptions

**Comment by ahmadmiraj** [comment]
@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
    private void makeAndAddView(View child) {

        FrameLayout.LayoutParams lp = (FrameLayout.LayoutParams) child.getLayoutParams();
        addViewInLayout(child, 0, lp, true);

        final boolean needToMeasure = child.isLayoutRequested();
        if (needToMeasure) {
            int childWidthSpec = getChildMeasureSpec(getWidthMeasureSpec(),
                    getPaddingLeft() + getPaddingRight() + lp.leftMargin + lp.rightMargin,
                    lp.width);
            int childHeightSpec = getChildMeasureSpec(getHeightMeasureSpec(),
                    getPaddingTop() + getPaddingBottom() + lp.topMargin + lp.bottomMargin,
                    lp.height);
            child.measure(childWidthSpec, childHeightSpec);
        } else {
            cleanupLayoutState(child);
        }


        int w = child.getMeasuredWidth();
        int h = child.getMeasuredHeight();

        int gravity = lp.gravity;
        if (gravity == -1) {
            gravity = Gravity.TOP | Gravity.START;
        }


        int layoutDirection = getLayoutDirection();
        final int absoluteGravity = Gravity.getAbsoluteGravity(gravity, layoutDirection);
        final int verticalGravity = gravity & Gravity.VERTICAL_GRAVITY_MASK;

        int childLeft;
        int childTop;
        switch (absoluteGravity & Gravity.HORIZONTAL_GRAVITY_MASK) {
            case Gravity.CENTER_HORIZONTAL:
                childLeft = (getWidth() + getPaddingLeft() - getPaddingRight()  - w) / 2 +
                        lp.leftMargin - lp.rightMargin;
                break;
            case Gravity.END:
                childLeft = getWidth() + getPaddingRight() - w - lp.rightMargin;
                break;
            case Gravity.START:
            default:
                childLeft = getPaddingLeft() + lp.leftMargin;
                break;
        }
        switch (verticalGravity) {
            case Gravity.CENTER_VERTICAL:
                childTop = (getHeight() + getPaddingTop() - getPaddingBottom()  - h) / 2 +
                        lp.topMargin - lp.bottomMargin;
                break;
            case Gravity.BOTTOM:
                childTop = getHeight() - getPaddingBottom() - h - lp.bottomMargin;
                break;
            case Gravity.TOP:
            default:
                childTop = getPaddingTop() + lp.topMargin;
                break;
        }

        child.layout(childLeft, childTop, childLeft + w, childTop + h);
    }

**Comment by ahmadmiraj** [comment]
this is my class

**Comment by ahmadmiraj** [comment]
package com.lorentzos.swipecards;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Toast;

import com.lorentzos.flingswipe.SwipeFlingAdapterView;
import com.lorentzos.swipecards.adapter.SwipViewAdapter;
import com.lorentzos.swipecards.model.SwipModel;

import java.util.ArrayList;

import butterknife.ButterKnife;
import butterknife.InjectView;
import butterknife.OnClick;


public class MyActivity extends Activity {

    public static ArrayList<SwipModel> al;
    private ArrayAdapter<String> arrayAdapter;
    public SwipViewAdapter swipViewAdapter;
    private int i;

    @InjectView(R.id.frame) SwipeFlingAdapterView flingContainer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my);
        ButterKnife.inject(this);

        al = new ArrayList<>();
        al.add(new SwipModel("php","Description"));
        al.add(new SwipModel("c","Description"));
        al.add(new SwipModel("python","description"));
        al.add(new SwipModel("java","description"));
        al.add(new SwipModel("html", "description"));
        al.add(new SwipModel("c++","description"));
        al.add(new SwipModel("css", "description"));
        al.add(new SwipModel("javascript","description"));

        swipViewAdapter = new SwipViewAdapter(getApplicationContext(),al);
//        swipViewAdapter = new ArrayAdapter<>(this, R.layout.item, R.id.helloText, al );


        flingContainer.setAdapter(swipViewAdapter);
        flingContainer.setFlingListener(new SwipeFlingAdapterView.onFlingListener() {
            @Override
            public void removeFirstObjectInAdapter() {
                // this is the simplest way to delete an object from the Adapter (/AdapterView)
                Log.d("LIST", "removed object!");
                al.remove(0);
                arrayAdapter.notifyDataSetChanged();
            }

            @Override
            public void onLeftCardExit(Object dataObject) {
                //Do something on the left!
                //You also have access to the original object.
                //If you want to use it just cast it (String) dataObject
                makeToast(MyActivity.this, "Left!");
            }

            @Override
            public void onRightCardExit(Object dataObject) {
                makeToast(MyActivity.this, "Right!");
            }

            @Override
            public void onAdapterAboutToEmpty(int itemsInAdapter) {
                // Ask for more data here
//                al.add("XML ".concat(String.valueOf(i)));
//                arrayAdapter.notifyDataSetChanged();
//                Log.d("LIST", "notified");
//                i++;
            }

            @Override
            public void onScroll(float scrollProgressPercent) {
                View view = flingContainer.getSelectedView();
                view.findViewById(R.id.item_swipe_right_indicator).setAlpha(scrollProgressPercent < 0 ? -scrollProgressPercent : 0);
                view.findViewById(R.id.item_swipe_left_indicator).setAlpha(scrollProgressPercent > 0 ? scrollProgressPercent : 0);
            }
        });


        // Optionally add an OnItemClickListener
        flingContainer.setOnItemClickListener(new SwipeFlingAdapterView.OnItemClickListener() {
            @Override
            public void onItemClicked(int itemPosition, Object dataObject) {
                makeToast(MyActivity.this, "Clicked!");
            }
        });

    }

    static void makeToast(Context ctx, String s){
        Toast.makeText(ctx, s, Toast.LENGTH_SHORT).show();
    }


    @OnClick(R.id.right)
    public void right() {
        /**
         * Trigger the right event manually.
         */
        flingContainer.getTopCardListener().selectRight();
    }

    @OnClick(R.id.left)
    public void left() {
        flingContainer.getTopCardListener().selectLeft();
    }

}

**Comment by ahmadmiraj** [comment]
package com.lorentzos.swipecards.adapter;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import com.lorentzos.swipecards.R;
import com.lorentzos.swipecards.model.SwipModel;

import java.util.ArrayList;

/**
 * Created by ahmad on 11/30/15.
 */
public class SwipViewAdapter  extends BaseAdapter {

    public static ArrayList<SwipModel> list;
    Context ctx;
    private LayoutInflater l_Inflater;
    ViewHolder holder;

    public SwipViewAdapter(Context mContext,ArrayList<SwipModel> arr) {
        this.ctx = mContext;
        list = arr;
        l_Inflater = LayoutInflater.from(ctx);
    }

    @Override
    public int getCount() {
        return list.size();
    }

    @Override
    public Object getItem(int i) {
        return list.get(i);
    }

    @Override
    public long getItemId(int i) {
        return i;
    }

    @Override
    public View getView(int i, View view, ViewGroup viewGroup) {
        if (view == null) {
            holder = new ViewHolder();
            view = l_Inflater.inflate(R.layout.swip_item, null);
            holder.title = (TextView) view.findViewById(R.id.title);
//            holder.image = (ImageView) view.findViewById(R.id.image);
            holder.description = (TextView) view.findViewById(R.id.description);
            view.setTag(holder);
        }
//        holder.image.setImageDrawable(list.get(i).getCardImageDrawable());
        holder.title.setText(list.get(i).getTitle());
        holder.description.setText(list.get(i).getDescription());
        return view;
    }
    static class ViewHolder {
        TextView title ;
        ImageView image;
        TextView description;
    }
}

**Comment by ahmadmiraj** [comment]
i will wait for answer please help me out !!

**Comment by ahmadmiraj** [comment]
i just trying to modify it according to my needs and it is not working and i ready have mention my logs above !!

**Comment by alexwalterbos** [comment]
@ahmadmiraj please format your code using markdown (by placing it between three ticks, see the markdown styling). It's not legible this way. You could also put it in a gist (gist.github.com). Start looking for that `NullPointer` on line 148 in this file (line taken from your stack trace)

`at com.lorentzos.flingswipe.SwipeFlingAdapterView.makeAndAddView(SwipeFlingAdapterView.java:148)`

I can't make up what goes wrong from your pasted code because of the formatting, unfortunately.

**Comment by ahmadmiraj** [comment]
thanx for the reply
here is a link of a google drive u will find everything over there.
https://drive.google.com/folderview?id=0B8UUy4Hs0DxFamlvelRWTmdoQnM&usp=sharing

**Comment by ahmadmiraj** [comment]
Any suggestions brother ?

**Comment by ahmadmiraj** [comment]
Any suggestions for me brother ??

**Comment by alexwalterbos** [comment]
Hard to tell, but I'm pretty sure this is the issue: change the `getView()` in your `SwipViewAdapter`:

```
    @Override
    public View getView(int i, View view, ViewGroup viewGroup) {
        if (view == null) {
            holder = new ViewHolder();
            view = l_Inflater.inflate(R.layout.swip_item, null); // null here should be viewGroup
            holder.title = (TextView) view.findViewById(R.id.title);
//            holder.image = (ImageView) view.findViewById(R.id.image);
            holder.description = (TextView) view.findViewById(R.id.description);
            view.setTag(holder);
        }
//        holder.image.setImageDrawable(list.get(i).getCardImageDrawable());
        holder.title.setText(list.get(i).getTitle());
        holder.description.setText(list.get(i).getDescription());
        return view;
    }
```

Make sure you understand why this is necessary: Android needs information about the parent views of the new one you are inflating, for purposes like measuring them; you can't inflate something without this information. It has to get that from whatever it is inflated 'into'; in this case that's the `viewGroup`, and that's also why it's an argument for the `getView()` method. 

Please close this issue if that solves the problem.

**Comment by ahmadmiraj** [comment]
Hi Alex !
Thanks for your reply,as previous recommendation , i have added the current view to viewGroup of the SwipeViewAdapter,but here is the exception i was found :
 java.lang.UnsupportedOperationException: addView(View) is not supported in AdapterView
Please me let me know with brief description,its the major issue ,we can say.

waiting for your response...

**Comment by alexwalterbos** [comment]
Can you show your updated `getView()`? To be clear, the third line of the `getView()` method as I posted should be this after updating: 
```
view = l_Inflater.inflate(R.layout.swip_item, viewGroup);
```

**Comment by ahmadmiraj** [comment]
Still no luck !

**Comment by alexwalterbos** [comment]
> Can you show your updated `getView()`?

**Comment by wyb20151010** [comment]
hello ahmadmiraj  and alexwalterbos 
i solve the problem through change my code ：

LayoutInflater.from(mContext).inflate(R.layout.item_theme_card,
                    null);
to：
LayoutInflater inflater = (LayoutInflater) mContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
convertView = inflater.inflate(R.layout.item_theme_card, parent, false);    

i hope my code will help you,but i actually don't understand why this way make it work?
i hope some guys can help me!!!

**Comment by wyb20151010** [comment]
@ahmadmiraj

**Comment by alexwalterbos** [comment]
You pass the parent to the inflater in your updated approach, and I've explained why that is necessary in a [previous comment here](https://github.com/Diolor/Swipecards/issues/126#issuecomment-164413101)

**Comment by wyb20151010** [comment]
when i first time open the app ,the image of the first card page can not show,when i open this activity second time the pic will show. it make  me so confusing.  can u help me out ??thanks   @alexwalterbos

**Comment by alexwalterbos** [comment]
That out of scope of this issue, and I don't have enough information to debug your app.  Please close this issue if you've got the adapter and the `getView()` method working (and please specify what finally made it work, so others can learn from this issue too). Regarding your issue with the image, that's likely an issue with the way you load your images; not with this library.

**Comment by wyb20151010** [comment]
ok,thanks for you help

**Comment by ahmadmiraj** [comment]
My issue is still there !

**Comment by wyb20151010** [comment]
@ahmadmiraj  poor kid,i help my answer will help you

**Comment by gakyoo** [comment]
@wyb20151010 Your solution worked for me too, thanks very much

**Comment by akhilkailas** [comment]
I get this kind of error whenever i try to set adapter,

 Process: in.gandiva.itfacts, PID: 6596
                                                 java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
                                                     at com.lorentzos.flingswipe.SwipeFlingAdapterView.makeAndAddView(SwipeFlingAdapterView.java:149)
                                                     at com.lorentzos.flingswipe.SwipeFlingAdapterView.layoutChildren(SwipeFlingAdapterView.java:132)
                                                     at com.lorentzos.flingswipe.SwipeFlingAdapterView.onLayout(SwipeFlingAdapterView.java:117)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                     at com.android.internal.policy.DecorView.onLayout(DecorView.java:751)
                                                     at android.view.View.layout(View.java:17866)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5757)
                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2724)
                                                 

I have tried several  methods but nothing went good, can someone help me??

**Comment by ashish4rawat** [comment]
Oh no
