### ISSUE TITLE
java.lang.IllegalStateException: Surface was already locked 

### ISSUE THREAD

**Issue by juanmartinbernal** [Diolor/Swipecards#137]
Hi, 
I get this error when I swype the cards.....

java.lang.IllegalStateException: Surface was already locked
	at android.view.Surface.lockCanvas(Surface.java:252)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2512)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2486)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2317)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1940)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1035)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5847)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
	at android.view.Choreographer.doCallbacks(Choreographer.java:593)
	at android.view.Choreographer.doFrame(Choreographer.java:562)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5336)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by alexwalterbos** [comment]
This is likely an issue that happens because you draw on your canvas 'manually', do you do that? If so, [this](http://stackoverflow.com/questions/8875702/android-canvas-locking-throws-illegalargumentexception) might help. If not, please post related code in your issue description.

**Comment by juanmartinbernal** [comment]
Hi,

I use library Swipecards by Lorenzo, this error apper in android version Android 4.4 y device Huawei, but 
happens occasionally....

**Comment by juanmartinbernal** [comment]
this is my code....
SwipeFlingAdapterView flingContainer;
 myAppAdapter = new MyAppAdapterCards(list, context);
        flingContainer.setAdapter(myAppAdapter);
        myAppAdapter.notifyDataSetChanged();

            flingContainer.setFlingListener(new SwipeFlingAdapterView.onFlingListener() {
                @Override
                public void removeFirstObjectInAdapter() {


                }

                @Override
                public void onLeftCardExit(Object dataObject) {
                           list.remove(0);
                             myAppAdapter.notifyDataSetChanged();
                           

                @Override
                public void onRightCardExit(Object dataObject) {
                            list.remove(0);
                             myAppAdapter.notifyDataSetChanged();
               }
                @Override
                public void onAdapterAboutToEmpty(int itemsInAdapter) {

                }

                @Override
                public void onScroll(float scrollProgressPercent) {

                    View view = flingContainer.getSelectedView();
                    if(view != null) {
                        view.findViewById(R.id.backgroundFrame).setAlpha(0);
                        view.findViewById(R.id.item_swipe_right_indicator).setAlpha(scrollProgressPercent < 0 ? -scrollProgressPercent : 0);
                        view.findViewById(R.id.item_swipe_left_indicator).setAlpha(scrollProgressPercent > 0 ? scrollProgressPercent : 0);
                    }
                }
            });

         
                flingContainer.setOnItemClickListener(new SwipeFlingAdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClicked(int itemPosition, Object dataObject) {
                        // Log.d("click", "click card");
                     }});
           }

**Comment by juanmartinbernal** [comment]
Note:

MyAdapter have ImageView and TextView and load image with Picasso in my ImageView....
